### PR TITLE
Material UI theming

### LINKED ISSUE #1884: Feature Request: Indication of Which Organization You Are In
**Problem**
With a Multi-Org set up, once you select an org from the drop down, there is no indication of which org you are in besides the organization id in the url. Looking at the UI itself, however, I can't tell which organization I'm in.

**Solution**
Have a header that says the name of the org at the top or highlight the org you are in within the drop down menu.

**Context**
Header could be above the "Campaigns" title or some marker in the drop down menu
Screen Shot 2020-11-09 at 12 06 31 PM
Screen Shot 2020-11-09 at 12 06 41 PM

### PR DESCRIPTION
**Pull request by stefanhayden**
# Fixes #1884 #1504

## Description

This PR takes advantage of the move to use the most up to date Material UI and its ability to theme. There is now a ThemeProvider. If you want to access the theme from any component just wrap it in the `withMuiTheme` higher order component which will pass in `muiTheme` as a prop in to your component.

example

image

image

image

# Checklist:

- [ x ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by crayolakat** [comment]
Hi Stefan! Here is a piece of feedback that we got from QA'ing your PR:
The secondary color is default set to #ffffff, and this causes several buttons with color="secondary" set to be invisible. E.g.: See attached screenshot where the "Add new canned response" button is invisible
Screen Shot 2021-10-06 at 2 31 32 PM

Is it possible to make it so that people can't set the secondary color to white or any other hard to see colors?

**Comment by stefanhayden** [comment]
thanks for testing and thanks for the feed back. I've done a bunch of refactoring and I think the experience is much better now. One thing that is weird about this app is there really isn't much use of a secondary color. I think as we change that's something we can think more about. 

I've change the default secondary color from `#FFFFFF` to `#555555`. I've also grabbed a library call `color-difference` that finds the distance of two colors from 0 to 100 (back and white would be 100). I've eye balled what made sense to me and now show an error and stop form submission if that number is 20 or below. Originally I tried a library that measured contrast difference but actually the default theme of Spoke fails having enough contrast with the green on white. something to think about for the future. Also in the future this can be updated to account for dark mode as well (which with this change out app not fully supports if we had an interface for).

example

I've also updated the `GSColorPicker` to default have an error if a non-valid hex code is passed in. 

here is what that "Add new canned response" button looks like now: 
image

**Comment by crayolakat** [comment]
Thanks Stefan! Some additional feedback:

There are still references to theme in `src/containers/Settings/index.jsx`, causing a blank screen when trying to view the Settings page in some organizations. I replaced the `theme` references with `muiTheme` in my QA branch (https://github.com/MoveOnOrg/Spoke/commit/7dacc052b1560b688aa1cb9e7fcffe44f5e5be9e), and the Settings page is loading now. There is this error in the console however: ```The prop `open` is marked as required in `ForwardRef(Dialog)`, but its value is `undefined`.```
image

**Comment by stefanhayden** [comment]
@crayolakat I updated those colors and found more I also missed. I could not get that error to show. I tested both on this branch and your `stage-main-11-1-material-ui-theming2` branch. Do you have any additional steps to reproduce?

**Comment by crayolakat** [comment]
@stefanhayden After doing a bit of digging, I figured out that this issue isn't related to your PR, and is also present in the current release of Spoke. I documented the issue and reproduction steps here: https://github.com/MoveOnOrg/Spoke/issues/2060

Thank you so much  for the updates. I will run your PR through another round of QA, and let you know if there's any additional feedback!

**Review by crayolakat — CHANGES_REQUESTED** [review]
Hi Stefan! 2 pieces of feedback:

1. When creating a new campaign, the "Primary color" input field is marked red with the message "Invalid color" when the field is blank. However, a blank value is a valid value since the "Primary color" field isn't a required field, and if the campaign is created without a "Primary color" input, it uses the default color with no issues
image
2. The app now crashes in the Texter TODO view if an invalid "Primary color" value is entered. Can this behavior be modified to how it currently is on the `main` branch, and use the default color if the "Primary color" value is invalid?
image

**Comment by stefanhayden** [comment]
oops! I'll have it fixed by Monday! thanks!

**Comment by stefanhayden** [comment]
@crayolakat this should be fixed now.

**Review by crayolakat — APPROVED** [review]
Looks good, thanks!!

**Pull request merged**
