### PR TITLE
1014 easy multiple campaign archiving

### LINKED ISSUE #1014: Archiving multiple campaigns needs to be easier
Need to be able to tick a box on each campaign to archive a bunch. As it is now, can archive only one at a time, then have to start over searching for more. @bdatkins 
@lperson @codygordon @joemcl

### PR DESCRIPTION
**Pull request by azuzunaga**
Resolves MoveOnOrg/Spoke#1014.

The archiving multiple campaigns option is hidden in a menu:

Apr-05-2019 12-02-28

@suegibson: there is more room in the menu for "bulk" archiving actions, if you think they will be helpful. If so, can the campaigns you archive be categorized (e.g. older than 2 weeks, all texts sent, etc.)?

### CODE REVIEW

**Comment by suegibson** [comment]
Thank you, Americo. They can be categorized by candidate name or by State.

**Comment by azuzunaga** [comment]
Thanks @suegibson! The feature I was thinking about had more to do with categories that don't change across campaigns.

Let me think about implementing an "Archive campaign by ____" feature, but for now I think this should address your original [issue](https://github.com/MoveOnOrg/Spoke/issues/1014).

**Comment by suegibson** [comment]
> Thank you, Americo. They can be categorized by candidate name or by State.

I think I led you astray with this^^^response, @azuzunaga . I really need a box on each campaign in Current Campaigns view so I can select the campaigns I want to archive.

**Comment by azuzunaga** [comment]
No worries, @suegibson! That feature should be all set.

**Comment by shakalee14** [comment]
hey @azuzunaga - can you resolve these merge conflicts so we can get this QA'd this week? thank you so much!

**Comment by azuzunaga** [comment]
All set @shakalee14, sorry I missed the merge conflict before!

**Pull request merged**
