### PR TITLE
Bugfix1218

### LINKED ISSUE #1218: Bug: Change text in Invite New Texters link in People
**Describe the bug**
Change
```Send your texting volunteers this link! Once they sign up, they'll be automatically assigned to this campaign.``` 
to
```Send your texting volunteers this link! Once they sign up, they'll be automatically assigned to this *Organization*.```

**To Reproduce**
go to People
Click on big + icon in lower right corner

**Expected behavior**
See #1022 

**Screenshots**
SpokeNewTextersLink

**Platform (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Chrome 
 - Desktop 
 - Version - ? 

**Additional context**

### PR DESCRIPTION
**Pull request by WSINTRA**
# Fixes #1218 
## Description
Changed the 
"Send your texting volunteers this link! Once they sign up, they'll be automatically assigned to this campaign."
to
"Send your texting volunteers this link! Once they sign up, they'll be automatically assigned to this (Organization || Campaign)" depending on whether or not a campaignId is passed as a prop.
Created a __test__ file to confirm changes in __test__/components/OrganizationJoinLink.test.js
screenshot

# Checklist:
- [x ] I have manually tested my changes on desktop and mobile
- [x ] The test suite passes locally with my changes
- [x ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [x ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [n/a ] I have made any necessary changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- [n/a ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Review by shakalee14 — DISMISSED** [review]

**Comment by ibrand** [comment]
Hey @WSINTRA I'm realizing that I think you made this PR before we ran prettier on the whole codebase which is causing a few merge conflicts as I'm trying to merge in your changes.

Would you be up for running the following to correct merge conflicts and then tag me again on this PR so I can get you merged?

1. `git pull origin main` -- this will pull from our main branch to update all your files and will show you the merge conflict I'm seeing in your file related to double vs. single quotes
2. Make sure your change works by running `yarn dev` and double checking it
3. Make sure tests still pass with `yarn test`
4. `git push` and ping me!

I know this looks like a lot, but it shouldn't take long since your conflict isn't major. I really appreciate your submission and can't wait to merge!

**Comment by WSINTRA** [comment]
I'm getting ...

> $ git pull origin main --
>
> From https://github.com/WSINTRA/Spoke
>
>  * branch              main       -> FETCH_HEAD
>
> Already up to date.
>
Fullstack Developer <http://www.formasimplex.com>
www.formasimplex.com
LinkedIn <https://www.linkedin.com/in/william-robert-simpson>

**Comment by WSINTRA** [comment]
Sorry forgot to fetch from main repository, just fixing it now
Fullstack Developer <http://www.formasimplex.com>
www.formasimplex.com
LinkedIn <https://www.linkedin.com/in/william-robert-simpson>

**Comment by WSINTRA** [comment]
* PASS * __test__/components/*OrganizationJoinLink.test.js*

  OrganizationJoinLink tests A

    ✓ finds proper text for invite when campaignId is present (6ms)

  OrganizationJoinLink tests B

    ✓ finds proper text for invite when capaignId is null (2ms)


git add src/components/OrganizationJoinLink.jsx

Music_Studio@home:*~/Development/Spoke/Spoke*$ git commit -m "merge
conflict fixed, in OrganizationJoinLink.jsx"

[bugfix1218 7ec14b49] merge conflict fixed, in OrganizationJoinLink.jsx

Music_Studio@home:*~/Development/Spoke/Spoke*$ git push

Counting objects: 7, done.

Delta compression using up to 8 threads.

Compressing objects: 100% (7/7), done.

Writing objects: 100% (7/7), 755 bytes | 755.00 KiB/s, done.

Total 7 (delta 6), reused 0 (delta 0)

remote: Resolving deltas: 100% (6/6), completed with 6 local objects.

To https://github.com/WSINTRA/Spoke.git

   cae2f316..7ec14b49  bugfix1218 -> bugfix1218

Music_Studio@home:*~/Development/Spoke/Spoke*$

**Comment by ibrand** [comment]
Thank you @WSINTRA ! I ended up deleting my comment because I figure since the prettier addition was on our end, I might as well fix it, but I really appreciate you going ahead and fixing it! That really helps my work 🚀 

We'll be merging this to stage soon. Thanks again for getting started with Spoke, and looking forward to having you as a member of our contributor community 💯

**Review by ibrand — APPROVED** [review]

**Comment by joemcl** [comment]
OK but - I believe a Spoke instance has to have at least one Organization by default - and the join link is in People, not per (Spoke) Campaign. Alternating that text between 'organization or campaign' is confusing. So how about this @schuyler1d @ibrand @WSINTRA - rather than 'organization', the link text populates with whatever the *actual name of the Organization* is that was created on first deploy - so it could be Joe Blow for City Council Campaign, People for Action Organization, whatever.

**Pull request merged**
