### PR TITLE
Added 2 React component tests

### PR DESCRIPTION
**Pull request by briantam23**
Added React component tests for `TopNav.jsx` and `AssignmentTexterSurveys.jsx`

### CODE REVIEW

**Review by ibrand — DISMISSED** [review]
Awesome. Thanks for this @briantam23, my one question for you is whether we should try and test the advancement of interaction steps in `__test__/components/AssignmentTexterSurveys.test.js`. I see you're testing the rendering at this point, but should we test some of the functions within the component?

**Comment by briantam23** [comment]
No problem. I just wanted to get in a couple of simple tests as I was having trouble with my tests passing locally but not with TravisCI. I will work on function testing this weekend!

**Review by schuyler1d — DISMISSED** [review]
Great start!  Thank you!

**Comment by briantam23** [comment]
Awesome, thank you!

**Comment by ibrand** [comment]
Hey @briantam23 do you mind merging main into your PR since we merged a few new things into main? We'll merge this in the next cycle. That'd look like this:

```
git pull upstream main
git push
```

**Comment by briantam23** [comment]
Okay, I will do it first thing Saturday morning!

**Comment by briantam23** [comment]
Done!

**Review by ibrand — APPROVED** [review]

**Pull request merged**
