### PR TITLE
Stage main

### PR DESCRIPTION
**Pull request by ibrand**
@filafb
#1175

@lperson
~#1178~ [**reverted**](https://github.com/MoveOnOrg/Spoke/pull/1203/commits/78fc25011c7aba8d2489b246d56b0fdeb9a0edc3)
#1189

@schuyler1d 
#1173 

@shakalee14 
#1222

### CODE REVIEW

**Comment by shakalee14** [comment]
See comment here about the react-formal update: https://github.com/MoveOnOrg/Spoke/pull/1178#issuecomment-523073842

**Comment by shakalee14** [comment]
@ibrand  - can we add https://github.com/MoveOnOrg/Spoke/pull/1173?

**Comment by ibrand** [comment]
@shakalee14 yeah I can add that in! Should I re-run prettier on that new patch as well? Or do you want to do it?

**Comment by shakalee14** [comment]
After deploying to stage, we're getting an "There was an error creating your campaign" when clicking the green plus button in the admin campaigns view (/admin/1/campaigns). This is connected to this issue: https://github.com/MoveOnOrg/Spoke/issues/1196.

```
9:52:14 AM server.1               |  TypeError: Cannot read property 'indexOf' of undefined
9:52:14 AM server.1               |      at _callee2$ (/Users/shaka/moveon/Spoke/src/server/api/schema.js:21
9:52:14 AM server.1               |  >  8:15)
9:52:14 AM server.1               |      at tryCatch (/Users/shaka/moveon/Spoke/node_modules/babel-runtime/n
9:52:14 AM server.1               |  >  ode_modules/regenerator-runtime/runtime.js:62:40)
```

We can only reproduce this issue when we're running v10.15.3 (not our suggested 10.3).

**Review by shakalee14 — APPROVED** [review]

**Pull request merged**
