### PR TITLE
Solve 2084

### LINKED ISSUE #2084: Bug: Buggy getActionChoiceData; bad reference implementations for Spoke action handlers.
Spoke has two action handlers "that don't do much, but they serve as reference implementations":

- `test-action`
- `complex-text-action`

Unfortunately, the method signatures provided are inaccurate and misleading for people rolling their own action handlers. For example, the `available` handler is represented as:

```
// return true, if the action is usable and available for the organizationId
// Sometimes this means certain variables/credentials must be setup
// either in environment variables or organization.features json data
// Besides this returning true, "test-action" will also need to be added to
// process.env.ACTION_HANDLERS
export async function available(organizationId) {
  return {
    result: true,
    expiresSeconds: 600
  };
}
```

The problem with this that the actual argument is an `organization` argument, not the identifier for an argument. This can be seen in the `getActionHandlerAvailability` method in `src/extensions/action-handlers/index.js`, which is a method for calling the `available` method on action handlers. Note that the method passes an `organization` argument not its id.

```
export async function getActionHandlerAvailability(
  name,
  actionHandler,
  organization,
  user
) {
  const fallbackFunction = async (_actionHandler, _organization, _user) => {
    exports.validateActionHandler(_actionHandler);
    return actionHandler.available(_organization, _user);
  };

/* ... */

}
```
There is also the `processAction` method. For `test-action`, the signature is:

```
// What happens when a texter saves the answer that triggers the action
// This is presumably the meat of the action
export async function processAction({
  campaignContactId,
  contact
  // campaign,    // unused parameter
  // organization // unused parameter
}) {

```
For `complex-text-action`, the signature is:

```
// What happens when a texter saves the answer that triggers the action
// This is presumably the meat of the action
export async function processAction({
  interactionStep,
  campaignContactId,
  contact
}) {
```

The problem with these examples is that they don't tell action handler programmers the full possibilities of arguments passed to `processAction`. If you look at `questionResponseActionHandler` in `src/workers`, you see the full signature as:

```
const questionResponseActionHandler = async ({
  name,
  organization,
  questionResponse,
  interactionStep,
  campaign,
  contact,
  wasDeleted,
  previousValue
}) => {
  const handler = await ActionHandlers.rawActionHandler(name);

  if (!wasDeleted) {
    // TODO: clean up processAction interface
    return handler.processAction({
      questionResponse,
      interactionStep,
      campaignContactId: contact.id,
      contact,
      campaign,
      organization,
      previousValue
    });
  } else if (
    handler.processDeletedQuestionResponse &&
    typeof handler.processDeletedQuestionResponse === "function"
  ) {
    return handler.processDeletedQuestionResponse({
      questionResponse,
      interactionStep,
      campaignContactId: contact.id,
      contact,
      campaign,
      organization,
      previousValue
    });
  }
};

```
In `complex-test-action`, the parameters for `processDeletedQuestionResponse` isn't well documented either.

```
// What happens when a texter remotes an answer that triggers the action
export async function processDeletedQuestionResponse(options) {
```

Finally, while investigating this issue, I discovered a bug in `getActionChoiceData` in `src\extensions\action-handlers\index.js`; this is relevant because this is the code that calls `clientChoiceDataCacheKey` in action handlers. Look at the code (especially `cacheKeyFunc`, the code that represents `clientChoiceDataCacheKey`):

```
export async function getActionChoiceData(actionHandler, organization, user) {
  const cacheKeyFunc = actionHandler.clientChoiceDataCacheKey || (() => "");
  const clientChoiceDataFunc =
    actionHandler.getClientChoiceData || (() => ({ data: "{}" }));

  let cacheKey;
  try {
    cacheKey = exports.choiceDataCacheKey(
      actionHandler.name,
      organization,
      cacheKeyFunc(user)
    );
  } catch (caughtException) {
    log.error(
      `EXCEPTION GENERATING CACHE KEY for action handler ${actionHandler.name} ${caughtException}`
    );
  }
```

But the signature for export function clientChoiceDataCacheKey(organization, user) { is:

```
export function clientChoiceDataCacheKey(organization, user) {
```
The `organization` parameter is actually `user`, and organizational data is nowhere to be seen. 

(**To Reproduce**, **Expected behavior**,  **Screenshots**,  **Platform**,  **Additional context**: N/A)

### PR DESCRIPTION
**Pull request by peterkmurphy**
# Fixes #2084 

## Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change, and any blockers that make your change a WIP_

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [X] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [X] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by Arique1104** [comment]
Hey @peterkmurphy, first of all, thank you so much for your contribution! 

It does looks like some of the builds are not passing our automated testing.  Would you be willing to make edits that are compatible with our code base?

**Comment by peterkmurphy** [comment]
Good day, @Arique1104 . I'd be _delighted_ to have code that is compatible with your code base. Unfortunately, when I look at what is breaking the tests, I observe:

```
Run yarn test
yarn run v1.22.17
$ jest --forceExit --runInBand --detectOpenHandles --verbose=false
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "true".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

It's not a case of test `A` in testSuite `B` failing, which would tell me whether my code is compatible or not. All unit tests pass on my computer.

This is the same behavior as pull request #2086 .

**Comment by Arique1104** [comment]
@peterkmurphy, during the HackNight being hosted right now we're noticing similar tests failing with the same error message.  

We're working on it currently to figure out how to resolve it.  

If we find a solution tonight, I will be happy to share the work around with you.  Or maybe resolve it without any additional work on your end. 

My apologies for not being more thorough and reviewing all the error messages and thank you for your patience.

**Comment by peterkmurphy** [comment]
It's all good, @Arique1104. I am glad that I am not the only one getting those issues with testing. Thank you and please let me know what is happening.

**Review by crayolakat — DISMISSED** [review]
Thank you for the detailed report of the bugs and fix!

Due to an existing bug, the automated tests all show as fail in this PR. That bug has been fixed here: https://github.com/MoveOnOrg/Spoke/pull/2090

I tested pulling the changes from that PR into your PR in a separate branch, and the automated tests pass!

**Review by crayolakat — APPROVED** [review]

**Pull request merged**
