### PR TITLE
Paginated campaigns list with searching and sorting

### LINKED ISSUE #1332: Paginated campaigns page with searching and sorting
As part of RFC #1320 and the project [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14), merge the work in this WorkingFamiles/Spoke PR:
- [116](https://github.com/WorkingFamilies/Spoke/pull/116)

### PR DESCRIPTION
**Pull request by lperson**
# Fixes #1332 

## Description

* paginated campaigns on campaigns page page (default = 50, other choices = 10, 25 and 100)
* paging widget also appears at the bottom of the campaigns list
* campaigns on campaigns page can be sorted by id ascending or descending (which is effectively the order the campaigns were created), due date ascending or descending, or title (default search is id ascending for current campaigns and id descending for archived campaigns)
* campaigns page has a search bar

Screen Shot 2019-12-28 at 5 08 22 PM

Screen Shot 2019-12-28 at 5 08 43 PM

This is a huge PR.  Sorry.

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes
- [x] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- NA ~I have made any necessary changes to the documentation~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Review by joemcl — APPROVED** [review]
OK so this works as described. I do note that I got spinning on campaign creation when clicked on Script Import which is not enabled anyway, but I was able to start the campaign anyway.

**Comment by ibrand** [comment]
Just a note here that this also fixes #1007 and to close that one when this is merged. Thanks @lperson !

**Comment by ibrand** [comment]
@lperson can we break this into 3?

Suggestion for breaking points:
PR 1:
- paginated campaigns on campaigns page page (default = 50, other choices = 10, 25 and 100)
- paging widget also appears at the bottom of the campaigns list

PR 2:
- campaigns on campaigns page can be sorted by id ascending or descending (which is effectively the order the campaigns were created), due date ascending or descending, or title (default search is id ascending for current campaigns and id descending for archived campaigns)

PR 3:
- campaigns page has a search bar

Then if anything goes wrong, it's a lot easier to revert based on which feature is breaking and to see errors more clearly.

**Review by schuyler1d — APPROVED** [review]
I know this is an old PR, but I'm approving after testing it and will be aiming for 5.5 release for this.

**Pull request merged**
