### PR TITLE
Drop deprecated babel presets.

### PR DESCRIPTION
**Pull request by jmcarp**

### CODE REVIEW

**Review by shakalee14 — APPROVED** [review]

**Comment by jmcarp** [comment]
Looks like I mixed up the order of presets in `.babelrc`. I fixed the order, and the campaigns page is working for me again.

**Comment by jmcarp** [comment]
@shakalee14: this is ready for review when you're available!

**Comment by lady3bean** [comment]
When logged in as an admin, I'm still seeing the `Field error: value is not an instance of Date`

The campaigns page at http://localhost:3000/admin/1/campaigns doesn't load beyond the nav, the dropdown menu where it says "current", and the button to make a new campaign. 

When I click to make a new campaign, I get this error:

```
AdminCampaignList.jsx:37 Uncaught (in promise) Error: TypeError: Cannot read property 'getHostNode' of null
    at AdminCampaignList._callee$ (http://localhost:3000/assets/bundle.js:178210:22)
    at tryCatch (http://localhost:3000/assets/bundle.js:178400:41)
    at Generator.invoke [as _invoke] (http://localhost:3000/assets/bundle.js:178634:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/assets/bundle.js:178452:22)
    at step (http://localhost:3000/assets/bundle.js:179088:31)
    at http://localhost:3000/assets/bundle.js:179099:14
    at <anonymous>
```

**Comment by jmcarp** [comment]
@lady3bean: I'm wondering if the error you're describing was an interaction with other outdated dependencies. After #399 was merged, I rebased this patch on master and reinstalled dependencies, and now dates are working as expected. Can you grab the updated patch and let me know if you continue seeing that issue?

**Comment by shakalee14** [comment]
@jmcarp - this branch fails to compile locally and gives this error in the client: 
```
./node_modules/rollbar/lib/parser.js
Module not found: Error: Can't resolve 'fs' in '/Users/---/---/Spoke/node_modules/rollbar/lib'
 @ ./node_modules/rollbar/lib/parser.js 7:9-22
 @ ./node_modules/rollbar/rollbar.js
 @ ./src/lib/log.js
 @ ./src/lib/index.js
 @ ./src/client/error-catcher.js
 @ ./src/client/index.jsx
 @ multi webpack/hot/only-dev-server webpack-dev-server/client?http://127.0.0.1:3000/ babel-polyfill ./src/client/index.jsx
```

**Pull request merged**
