### PR TITLE
show all people in one page

### PR DESCRIPTION
**Pull request by lperson**
I'm not sure of the history here but it looks like there was work done to paginate the people page, which was reverted, and then the people page didn't work at all.

Now the people page displays everyone in a single page.  Users can use search functions in the browser to find the person on the page.

I'd like to understand what the motivation for the pagination was (Was the query taking too long?  Was the graphql response taking too long?  Was the page failing to render?  Was it an attempt to improve usability?) and see if we need to reconsider this.  @joemcl -- thoughts?

### CODE REVIEW

**Comment by joemcl** [comment]
@lperson see https://github.com/MoveOnOrg/Spoke/pull/1077

**Comment by joemcl** [comment]
And @lperson was for speed, usability etc and still useful and needed.

**Comment by shakalee14** [comment]
FYI: we have this deployed now in production and we can only search people who are already apart of campaigns. Bringing up people in 'all campaigns' brings up a 'no results' dialogue or slows the browser. i have https://github.com/MoveOnOrg/Spoke/pull/1133 running in our production instance.

**Comment by lperson** [comment]
OMG I'll investigate!

> FYI: we have this deployed now and we can only search people who are already apart of campaigns. Bringing up people in 'all campaigns' brings up no results or slows the browser.

**Comment by lperson** [comment]
@shakalee14 can we clarify *where* it was deployed and *what* was deployed?

**Comment by shakalee14** [comment]
> @shakalee14 can we clarify _where_ it was deployed and _what_ was deployed?

i updated the original comment to clarify.

**Comment by lperson** [comment]
@shakalee14 thanks for updating.  How many users does MoveOn have in production (slack me if this is not something you want to state publically)?  This is working for WFP in production and I just want to make sure that any code changes to address the problem are really fixes.

**Comment by shakalee14** [comment]
Merged with https://github.com/MoveOnOrg/Spoke/pull/1134/files

**Pull request closed without merging**
