### PR TITLE
Delete redis userKey on logout

### PR DESCRIPTION
**Pull request by azuzunaga**
Co-Authored-By: Shaka Lee <shakalee14@users.noreply.github.com>

Addresses #796

### CODE REVIEW

**Review by shakalee14 — APPROVED** [review]

**Review by shakalee14 — CHANGES_REQUESTED** [review]
Need to figure out another way to update roles.

**Review by schuyler1d — DISMISSED** [review]
Before merging, can you:
1. rename logoutUser to something like clearUserCache
2. call the same function (clearUserCache) in [editUser](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L379)

**Comment by schuyler1d** [comment]
I agree with @shakalee14 's implied hunch that the login-logout-login is actually related to https://github.com/MoveOnOrg/Spoke/pull/722

**Comment by shakalee14** [comment]
I'm wondering if it should expire AND have some form of manual updating. 

@schuyler1d  thoughts?

**Comment by shakalee14** [comment]
I think we can't actually expire it based on this:
https://stackoverflow.com/questions/16545321/how-to-expire-the-hset-child-key-in-redis

Also when attempting to do this, 
```
      await r.redis.multi()
        .hsetAsync(userKey, orgId, highestRole)
        .expire(userKey, 86400)
        .exec()
```
I get an error that it's not a function. I think @schuyler1d 's suggestions are fine.

**Comment by schuyler1d** [comment]
I think this will be folded into the user caching refactor work: https://github.com/MoveOnOrg/Spoke/issues/894
-- but yes, we should have a `clear()` method which is triggered on logout or any user change.

Depending on where @azuzunaga is on this, we might want to close this PR and wait for the refactor one.

**Pull request closed without merging**
