### PR TITLE
Update to opt-out message with generic all-campaign message

### PR DESCRIPTION
**Pull request by deasterdaywfp**
I am opting you out of text messages from our organization now. Have a good day!

### CODE REVIEW

**Comment by shakalee14** [comment]
hey @deasterdaywfp - this PR seems to include an email report, and some incoming message work (a long with updating the opt out message.

Can you either 
1) Send a smaller pr with commit https://github.com/MoveOnOrg/Spoke/pull/643/commits/174625a03220d03e0d17885c2ca2ab89227994a3 (which I believe actually updates the opt out message)

2) Or create a comment which let me knows everything that is included in this PR

Thanks! 
cc: @joemcl

**Comment by schuyler1d** [comment]
I would also prefer that the email report (which looks great!) be a function that can be imported and run rather than just a raw file, but I don't think this would be a blocker to merge that.  Let's just update the description of this pr, @deasterdaywfp @codygordon

**Comment by codygordon** [comment]
@shakalee14 and @schuyler1d, I'm pretty sure this PR was mistakenly opened and recent commits to our fork are being added to it.

If you are interested in using the email report feature I can open a separate PR for it, but you should close this one.

**Comment by shakalee14** [comment]
Thanks for the clarification @codygordon - we are interested in the email report feature & will close this one.

**Pull request closed without merging**
