### PR TITLE
Csv file upload

### LINKED ISSUE #2071: Bug: CSV Upload fails and has no error message when CSV headers are incorrect
**Describe the bug**
Although there is a message of what mandatory headers are required in the CSV Upload, we still require a clearer error message to instruct the user that the error is within their CSV headers.  Currently, all that happens is that the CSV attempts to upload, but then gives up and does not let the user know what they can do to correct the upload.

**To Reproduce**
1. Go to 'campaigns'
2. Create a CSV document where the header says cell_phone instead of cell
2. Click on 'CSV Upload'
4. See CSV Upload fail without any error messages to guide the user.

**Expected behavior**
We want to make a suggestion or have an error message pop out that provides the same information:

```
Your upload file should be in CSV format with column headings in the first row. You must include firstName, (or first_name),lastName(or last_name), and cell columns. If you include a zip column, we'll use the zip to guess the contact's timezone for enforcing texting hours. An optional column to map the contact to a CRM is external_idAny additional columns in your file will be available as custom fields to use in your texting scripts.
```

Specifically, we should add a reminder that if uploading from VAN, their header reads `cell_phone` and needs to be changed to `cell`

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Desktop

**Additional context**
This bug was brought to our attention by our partner organization StateVoices and is high priority because it caused a lot of confusion during this recent election cycle.  Must have bug fixed before end of January 2022, if not sooner

### PR DESCRIPTION
**Pull request by percworld**
# Fixes #2071
## Motivation 
When uploading a CSV file, the user would see no error but the contacts were not successfully uploaded, usually due to a missing field (Column Header).

## Problem definition
It became clear that the fields were not being read correctly, and this lead us to expand this ticket to create functionality to help the user with limited CSV file experience to upload. The app needed to understand other potential field names to correctly assign a column that is deemed required (requiredUploadFields).

## Solution

It was decided the to prep the incoming data before parsing callback function was performed. In doing so, a greater understanding of the hump camelization library and Papa.parse library was gained.  A solution was to transform the header correctly before initializing a parse.  The topLevelUploadFields was imported to the react-component which can use them to decide what to rename the column.

Listed Custom Fields after Parse - Successful Upload with headers that were entered in program-specific syntax (accidental VAN upload)
Listed Custom Fields after Parse

Sad Path - User is missing a firstName (Note SAVE button now is disabled)
Sad Path

---
### /src/lib/parse_csv.js - 
1. Changed the data type of topLevelUploadFields to an object
2. Missing fields and invalid fields have been updated
    * Method to reduce top level fields to ones that are missing
3. Top level fields are filtered out to give us an array of Custom fields 

---
## Testing 

Jest
---

 /__test__/extensions/contact-loaders/csv-upload.test.js
Added tests to translat headers relating to VAN files being accidentally uploaded via the CSV upload
Added tests to translate headers that may be of an unsupported syntax before parsing

Reflect new Icon addition in the UI (now failing and hashed out).  
   // verify state is updated
    expect(component.state.contactUploadError).toBe(
      "Missing fields: firstName"
    );
    //verified it's visible in interface in Cypress test
    expect(wrapper.find("#fieldError").prop("primary")).toBe(
      "Missing fields: firstName"
    );
Second expectation failure error (Jest can't find the id prop of the element):
failure error

Cypress
---
Field Error shows up here when requested and exists in the UI 
Added tests for CSV uploads relating to new validation method.
cy.get("#fieldError").contains("Missing fields: firstName");

### Co-authored with Michael Walker [Walker87 Github](https://github.com/MichaelEWalker87)

# Checklist:

- [X] I have manually tested my changes on desktop 
- [X] The test suite passes locally with my changes
    *Cypress Pass
     *Jest has one test hashed out  
- [X] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [X] I have made any necessary changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by crayolakat** [comment]
@percworld @Arique1104 Should this be an open PR?

**Comment by percworld** [comment]
Hi closed this one myself as it was a mistake on my part, I will link
correct pull request within the hour

**Comment by percworld** [comment]
Here is the correct PR: 2116 <https://github.com/MoveOnOrg/Spoke/pull/2116>
I had made a mistake submitting a PR to the spoke repo instead of percworld
(mine), Sorry about that! Thank you Kathy.
Chuck

**Comment by crayolakat** [comment]
@percworld No problem, thanks Chuck!

**Pull request closed without merging**
