### PR TITLE
Add HackNight working group to the CONTRIBUTING doc

### PR DESCRIPTION
**Pull request by ibrand**
Add our weekly working group and slack to the doc for new contributors!

### CODE REVIEW

**Comment by joemcl** [comment]
Re this - "We have a weekly(ish) working group at [Progressive HackNight](https://progressivehacknight.org) that organizes in the #wg-spoke_p2p_sms_tool channel in the slack" - you mean that's a channel in the Progressive Hack Night Slack? If so, how does one join that Slack, I don't see an obvious link at progressivehacknight.org . Looks like it's at https://progressivehacknight.slack.com/ .

**Comment by joemcl** [comment]
OK found this -"If you are interested in getting involved in a breakout group, contact the project leader from their Github issue below, join our Slack to connect with them directly, or keep an eye out for them at one of our future HackNights.".

**Comment by joemcl** [comment]
And I get this when clicking on the link - 
"This link is no longer active
If you have an email address ending in @progressivehacknight.org, you can join this workspace using that address. Otherwise, you’ll need to ask for a new link."

**Comment by joemcl** [comment]
and then I get this - 
"Don’t have an @progressivehacknight.org email address?
Contact the workspace administrator at ProgressiveHackNight for an invitation." 
Aargh. I have to ask for and use *another* e-mail to join the Slack? And/or I send an e-mail to organizers [at] proghacknight [dot] org which is the 'workspace administrator', asking for an invite using my default e-mail?

**Comment by ibrand** [comment]
Hey @joemcl I linked to the Progressive HackNight website rather than directly to the slack because Progressive HackNight is a group with its own norms and event times and so I'd like for folks to go to their website and get a sense of the event before clicking straight into a slack invite. They're NYC based (which is less relevant now because of the pandemic) but worth being aware of. I can reach out to the organizers to make sure that the link gets updated since it's a problem that it's broken!

I want CONTRIBUTING.md to accurately represent more of the mini spaces that coders organize in. So far, I think ProgCode is the most reliable online space for general spoke communication and Progressive HackNight is an event that has had a working group (formerly in person) since ~2016ish so it's overdue that we mention it

**Comment by joemcl** [comment]
@ibrand cool and I get it

**Review by JeremyParker — APPROVED** [review]
👍

**Pull request merged**
