### PR TITLE
Stage-main pre-8.0

### PR DESCRIPTION
**Pull request by schuyler1d**
## Included so far:
* https://github.com/MoveOnOrg/Spoke/pull/1702
* https://github.com/MoveOnOrg/Spoke/pull/1700
* https://github.com/MoveOnOrg/Spoke/pull/1699
* https://github.com/MoveOnOrg/Spoke/pull/1695
* https://github.com/MoveOnOrg/Spoke/pull/1691
* https://github.com/MoveOnOrg/Spoke/pull/1689
* https://github.com/MoveOnOrg/Spoke/pull/1688
* https://github.com/MoveOnOrg/Spoke/pull/1686
* https://github.com/MoveOnOrg/Spoke/pull/1678
* https://github.com/MoveOnOrg/Spoke/pull/1707 Legal-related changes for modifying first script
* https://github.com/MoveOnOrg/Spoke/pull/1706
* https://github.com/MoveOnOrg/Spoke/pull/1715
* recent:
* https://github.com/MoveOnOrg/Spoke/pull/1718
* https://github.com/MoveOnOrg/Spoke/pull/1704
* https://github.com/MoveOnOrg/Spoke/pull/1709
* https://github.com/MoveOnOrg/Spoke/pull/1711
* https://github.com/MoveOnOrg/Spoke/pull/1721
* https://github.com/MoveOnOrg/Spoke/pull/1718
* buying toll-free numbers (with "800")
* allowing owners to configure more org settings

## Next release:
* Canned response-tag association (@aschneit ) (https://github.com/MoveOnOrg/Spoke/pull/1705)
* Allow more timezone stuff settable by organization: https://github.com/MoveOnOrg/Spoke/pull/1682 (@schuyler1d )
* allowing Twilio message services not to be 'sticky' 

## Target Release Date: August 10th, 2020

#  Draft Release Notes

# v8.0

August 2020: Version 8.0
**Note: Dynamic assignment is changing!** Pay special attention to the write up. This new and improved dynamic assignment should make the dynamic assignment flow friendlier to coaching new texters, and assist the reassignment flow.

This is a major release and therefore requires a schema change. See the deploy steps section for details. Anything marked as experimental has not yet been tested on a production texting campaign. We're marking this as a major version update 8.0 because there are several backwards-incompatible changes that we believe are important and valuable.

### Backwards incompatible Changes
- **Dynamic Assignment is changing**: After a lot of feedback and some great inspiration from the [Warren Spoke](https://github.com/Elizabeth-Warren/Spoke) we're modifying dynamic assign. Texters will now request batch sizes instead of getting an endless stream of texts. The admin can customize the batch size and who is allowed to click request after their first batch. This feature is also optionally complemented by the new "release texts" feature which is mentioned under "New Features/Improvements"
- **Old Texter UI is _no longer supported_**: We removed the `DEPRECATED_TEXTERUI` env variable and the old Texter UI is officially phased out
- **Texter Sideboxes are now off by default**: You now need to enable options in organization Settings tab (they previously were just automatically enabled from the variable)
  - If your previously set TEXTER_SIDEBOXES, then you must add `default-dynamicassignment` (and we recommend adding other new ones listed in new features) for dynamic assignment to work. 
  - If you are not using additional/experimental sideboxes, we recommend removing this environment variable entirely, so new texter sideboxes in later versions will automatically be available.
  - HOLD_ENTER_KEY no longer exists as an option (it was deprecated in our last major version)
- For non-US or subscriber-only mode users ONLY -- if you enabled ALLOW_SEND_ALL=1 (if you did not, then DO not do this), then you'll need to check to enable that feature in the Settings panel of your organization (as a is_superadmin user)
- Initial text messages are editable -- we recommend allowing the (default) TEXTER_SIDEBOXES= to include `default-editinitial` to make this option more muted.
- the src/integrations/ directory is renamed src/extensions/ to indicate that it's not just integrations with 3rd parties but also components that extend the system itself (message-handlers, texter-sideboxes, dynamicassignment-batches, job-runners). If you added your own src/integrations/ items make sure they are moved, and relevant imports are changed.
* There is a small migration to the `campaign` table which needs to be run before/during migration (either by leaving/disabling SUPPRESS_MIGRATIONS="" or for [AWS Lambda, see the db migration instructions](https://github.com/MoveOnOrg/Spoke/blob/main/docs/DEPLOYING_AWS_LAMBDA.md#migrating-the-database)

### New Features/Improvements
- **_Experimental_ Phone number management for campaigns**: A much requested feature for scaling past the 400 phone numbers limit.
  - turn this on with `EXPERIMENTAL_CAMPAIGN_NUMBERS`
- **_Experimental_ Release Texts**: Dynamic Assignment will also include a way for texters to release texts! That way when a texter is done for the day they can release texts without admin needing to go in and reassign them.
  - Turn this on with <release texts var>
- **New legal compliance measures**: Spoke now has a few tweaks to keep up with the latest FCC rulings. [Here's some resources on those changes]--need-link
- **texter-sidebox extension improvements**: (SummaryComponent, Empty context)
- **new message-handler `to-ascii`**: converts smart quotes and special dash characters to ascii. That way unicode wont surprisingly enlarge the message size.
- VAN action handler improvements
- Allow for action handlers to be included in google doc imports
- Better docs for developer onboarding
- Ctrl-z and Ctrl-Enter to Send (and any letter key/Enter sends on initial texting page)
- For phone number purchase interface, entering "800" will buy toll-free numbers (instead of by-areacode)
- Admins can visit app/:organizationId/todos/other/:userId to look at another user's todos page.
- Additional organization settings available from the Settings section (If you have an existing instance, enable this with OWNER_CONFIGURABLE=ALL
- Phone number buying and Twilio multi org enabled by default for new installs -- 
- Phone number buying can purchase toll-free numbers with "800"
- Campaign "response window" defaults to 48 hours and can be changed per campaign and then queries in Message Review to find who hasn't responded past the window.  A default can be set in Organization Settings page (overriding defaults)

### Bug Fixes
- Fix VAN action handler with warehouse loader
- Block blank message sending
- Fixes needsResponseCount out of sync with optouts (auto and no message)
- fix GSScriptEditor for Safari browsers that auto-focus

### CODE REVIEW

**Comment by ibrand** [comment]
Would love to get #1704 into the **incoming** list too !

**Comment by schuyler1d** [comment]
> Would love to get #1704 into the **incoming** list too !

I put it in Anticipated -- tests need to pass first.

**Comment by ibrand** [comment]
Yep caught that and looks like @jeffm2001 make a fix for the failing tests @schuyler1d

**Comment by ibrand** [comment]
#  Draft Release Notes

# v8.0

August 2020: Version 8.0
**Note: Dynamic assignment is changing!** Pay special attention to the write up. This new and improved dynamic assignment should make the dynamic assignment flow friendlier to coaching new texters, and assist the reassignment flow.

This is a major release and therefore requires a schema change. See the deploy steps section for details. Anything marked as experimental has not yet been tested on a production texting campaign. We're marking this as a major version update 8.0 because there are several backwards-incompatible changes that we believe are important and valuable.

### Backwards incompatible Changes
- **Dynamic Assignment is changing**: After a lot of feedback and some great inspiration from the [Warren Spoke](https://github.com/Elizabeth-Warren/Spoke) we're modifying dynamic assign. Texters will now request batch sizes instead of getting an endless stream of texts. The admin can customize the batch size and who is allowed to click request after their first batch. This feature is also optionally complemented by the new "release texts" feature which is mentioned under "New Features/Improvements"
- **Old Texter UI is _no longer supported_**: We removed the `DEPRECATED_TEXTERUI` env variable and the old Texter UI is officially phased out
- **Texter Sideboxes are now off by default**: You now need to enable options in organization Settings tab (they previously were just automatically enabled from the variable)
  - If your previously set TEXTER_SIDEBOXES, then you must add `default-dynamicassignment` (and we recommend adding other new ones listed in new features) for dynamic assignment to work. 
  - If you are not using additional/experimental sideboxes, we recommend removing this environment variable entirely, so new texter sideboxes in later versions will automatically be available.
  - HOLD_ENTER_KEY no longer exists as an option (it was deprecated in our last major version)
- For non-US or subscriber-only mode users ONLY -- if you enabled ALLOW_SEND_ALL=1 (if you did not, then DO not do this), then you'll need to check to enable that feature in the Settings panel of your organization (as a is_superadmin user)
- Initial text messages are editable -- we recommend allowing the (default) TEXTER_SIDEBOXES= to include `default-editinitial` to make this option more muted.
- the src/integrations/ directory is renamed src/extensions/ to indicate that it's not just integrations with 3rd parties but also components that extend the system itself (message-handlers, texter-sideboxes, dynamicassignment-batches, job-runners). If you added your own src/integrations/ items make sure they are moved, and relevant imports are changed.

### New Features/Improvements
- **_Experimental_ Phone number management for campaigns**: A much requested feature for scaling past the 400 phone numbers limit.
  - turn this on with `EXPERIMENTAL_CAMPAIGN_NUMBERS`
- **_Experimental_ Release Texts**: Dynamic Assignment will also include a way for texters to release texts! That way when a texter is done for the day they can release texts without admin needing to go in and reassign them.
  - Turn this on with <release texts var>
- **New legal compliance measures**: Spoke now has a few tweaks to keep up with the latest FCC rulings. [Here's some resources on those changes]--need-link
- **texter-sidebox extension improvements**: (SummaryComponent, Empty context)
- VAN action handler improvements
- Allow for action handlers to be included in google doc imports
- Better docs for developer onboarding
- Ctrl-z and Ctrl-Enter to Send (and any letter key/Enter sends on initial texting page)
- For phone number purchase interface, entering "800" will buy toll-free numbers (instead of by-areacode)
- Admins can visit app/:organizationId/todos/other/:userId to look at another user's todos page.
- Additional organization settings available from the Settings section (If you have an existing instance, enable this with OWNER_CONFIGURABLE=ALL

### Bug Fixes
- Fix VAN action handler with warehouse loader
- Block blank message sending
- Fixes needsResponseCount out of sync with optouts (auto and no message)
- fix GSScriptEditor for Safari browsers that auto-focus

@schuyler1d I think these are in a pretty good state, I just need to figure out some of the env vars and put a little more info about texter sideboxes

**Review by ibrand — APPROVED** [review]
Hooray!

**Pull request merged**
