### PR TITLE
prevent addition of contacts after campaign starts

### PR DESCRIPTION
**Pull request by lperson**

### CODE REVIEW

**Comment by lperson** [comment]
closes #474 
for review @schuyler1d

**Comment by shakalee14** [comment]
This is great - we should qa this on stage but it works locally. I'm wondering if we can add a message in the UI too (vs just server side error log). Let me know what you think about that @lperson

**Review by shakalee14 — COMMENTED** [review]
It would be nice to also send a message to client/ux on why new upload is 'failing'

**Comment by lperson** [comment]
@shakalee14 Thanks for the review!

The changes in the UI in PR #473 blocks the change on the client side by closing the contacts panel if it's open when the campaign starts, and now allowing it to open if the campaign is already started.  This change is a backstop, and the attempt to upload contacts won't get to the server in most cases.

That having been said, I agree the error should be passed back to the client.  Should we iterate on this PR and update the code?  Or maybe merge this PR and open an issue to address passing the message back?

**Review by shakalee14 — APPROVED** [review]

**Comment by shakalee14** [comment]
Merged with #483

**Pull request closed without merging**
