### PR TITLE
Set up cypress and add campaign and sign up tests

### PR DESCRIPTION
**Pull request by matteosb**
# Fixes # (issue)
#1494 

## Description
 
Sets up Cypress for integration testing and adds a few tests: login and sign up with local-auth and a basic campaign flow. The only changes to application code are to pass data-test attributes in more places. 

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes
- [x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [x ] I have made any necessary changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Review by schuyler1d — DISMISSED** [review]
This all looks pretty reasonable.

I'm going to add this to qa-ready in order to get Cypress in, especially since it modfies some components.

**Comment by schuyler1d** [comment]
One request, can you update (possibly delete?)
https://github.com/MoveOnOrg/Spoke/blob/main/docs/EXPLANATION-end-to-end-tests.md
and update 
https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO-run_tests.md
it can be a two sentence "For end-to-end tests run `cypress ....`.  See Cypress documentation here for more details"

**Comment by matteosb** [comment]
@schuyler1d done

**Review by schuyler1d — APPROVED** [review]
:+1:

**Pull request merged**
