### PR TITLE
SQL - all responses to Initial text, substring JSON data

### PR DESCRIPTION
**Pull request by joemcl**
Added "all responses to Initial text, excluding opt-outs, and separate out JSON data from `custom_fields`"

# Fixes # (issue)

## Description

# Checklist:

- [NA ] I have manually tested my changes on desktop and mobile
- [ NA] The test suite passes locally with my changes
- [ NA] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ NA] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [Yes] I have made any necessary changes to the documentation
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by joemcl** [comment]
@deasterdaywfp FYI ^^^^

**Comment by joemcl** [comment]
thanks @ibrand - https://spoke-changes-pr-1261.herokuapp.com/ is a demo instance then? using pipeline or whatever Heroku thing?

**Comment by ibrand** [comment]
Yep @joemcl ! It says that I deployed it, but it's actually set to auto-deploy so that anyone can click to QA this PR. If you click that link, it'll launch a Spoke instance with this branch applied

**Comment by joemcl** [comment]
Aha cool, it's just SQL query doc update but got it, good to know, thanks.

**Comment by joemcl** [comment]
@ibrand when I go to https://spoke-changes-pr-1261.herokuapp.com/ and attempt to log in, I get this - 
```
This site can’t be reached 

The webpage at https://asdfasf/authorize?client_id=asdfasdf&response_type=code&redirect_uri=https%3A%2F%2Fspoke-changes-pr-1261.herokuapp.com%2Flogin-callback&scope=openid%20profile%20email&state=%2Finvite%2F87976981-4d7b-4e37-964f-ab3303f5523f&auth0Client=eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOS4xMC4wIn0%3D might be temporarily down or it may have moved permanently to a new web address.

ERR_NAME_RESOLUTION_FAILED
```

**Review by ibrand — APPROVED** [review]

**Pull request merged**
