### PR TITLE
tweak message sending and add some tests

### PR DESCRIPTION
**Pull request by schuyler1d**

### CODE REVIEW

**Comment by shakalee14** [comment]
interesting @schuyler1d - looks like code climate says there is 1 issue to fix?

**Review by shakalee14 — COMMENTED** [review]
Where is this disabling mms sending? After a round of QAing, I'm still able to send images via text locally.

**Comment by hiemanshu** [comment]
@schuyler1d How about adding a test case for where there are two URLs given, and only the first one is selected? Otherwise this looks good.

**Comment by schuyler1d** [comment]
ok added @hiemanshu 's test.  @shakalee14 I think we should just ignore this code climate 'issue'
I tried to refactor a bit, but it's not really giving me anything actionable to address "Function messageSenderCreator has a Cognitive Complexity of 8 (exceeds 5 allowed). Consider refactoring"

**Comment by schuyler1d** [comment]
Also, this does keep media parsing working -- one commit disables them, but then a latter commit enables them again (with a bit refactor to make it super-work) and adds tests to make sure it stays super-working.

**Review by shakalee14 — APPROVED** [review]

**Pull request merged**
