### PR TITLE
Update deps: material-ui and react-router

### PR DESCRIPTION
**Pull request by jparkrr**
See https://github.com/MoveOnOrg/Spoke/issues/479 for more details. But the short story is these are a few of the updates needed to be able to upgrade react in the future (they use `propTypes` from the main react package, which is deprecated).

Updating these two deps won't have any meaningful effect right away, so feel free to close this if you don't want to risk it. It's nice to get some work out of the way and stay semi-current though.

Overall I feel pretty confident that there won't be big issues, but not 100%.

# Material-ui 0.15.2 -> 0.18.7
- Material-ui keeps a good changelog of breaking changes, https://github.com/mui-org/material-ui/releases.
- I don't upgrade to the 1.x-beta branch because it might require more changes.
- v0.19 removes `react-tap-event-plugin` so we would need to replace all onTouchTaps with onClicks, so I don't upgrade to that. https://github.com/mui-org/material-ui/releases/tag/v0.19.0
- The only breaking change that seems applicable to Spoke is  in `CircularProgress`, which I've updated. See https://github.com/mui-org/material-ui/releases/tag/v0.16.0-rc1

 # React-router 2.5.2 -> 3.2.0
- react-router v3 seems like they only removed things that were already deprecated in v2, so we should be safe
- we use react-router-redux which is compatible with v3
- the latest version of react-router is v4, which is a complete rewrite and might need a lot of changes (v3 is still maintained though)

### CODE REVIEW

**Comment by shakalee14** [comment]
Hey this is awesome. We def need to update! - after doing a quick round of QA, i see the following styling regressions (maybe from material ui update?):

Admin Campaign Menu, + button to create a new campaign overlays awkwardly:

screen shot 2018-01-26 at 2 28 01 pm


Texter Campaign Menu, # of todos for texts hides behind 'SEND FIRST TEXT' and 'SEND REPLIES' buttons: 

screen shot 2018-01-26 at 2 27 52 pm

**Review by shakalee14 — CHANGES_REQUESTED** [review]
See comment :)

**Comment by jparkrr** [comment]
@shakalee14 thanks for checking it! I fixed those issues

**Comment by schuyler1d** [comment]
reopening after moving to main

**Comment by Frydafly** [comment]
hey @schuyler1d & @stefanhayden -- checking in whether this PR is still relevant after 2 years? or if it's at all related to current planned updates?

**Comment by schuyler1d** [comment]
let's close this.  This was great work but I don't think it informs the current update roadmap.

**Pull request closed without merging**
