### PR TITLE
HOWTO import 'scripts' from Google Docs

### LINKED ISSUE #1237: Add HOWTO doc re how to implement script import from Google Docs
Create HOWTO doc with steps to implement script import from Google Docs . Related to #1238 .

### PR DESCRIPTION
**Pull request by joemcl**
# Fixes #1237 

## Description
Documentation for script import from Google Docs

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [X ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by joemcl** [comment]
@lperson @deasterdaywfp FYI, any help updating step 2 is appreciated :)

**Comment by joemcl** [comment]
@lperson when you have a chance, please review. Also @ibrand how can @lperson get added to the Reviewers choices here? He just needs to accept the Code of Conduct stuff etc?

**Comment by ibrand** [comment]
Sorry I missed this comment @joemcl, yep @lperson has been invited to be a core contributor and he needs to let me know / decide for himself if he'd like to accept! Anyone who meets the criteria of [submitting at least 3 pull requests that follow the PR template](https://github.com/MoveOnOrg/Spoke/wiki/Spoke-Access-Groups#spoke-core-contributors) can be invited to be a core contributor

**Comment by lperson** [comment]
Please close this.  It is replaced by #1268.

**Comment by ibrand** [comment]
Closing in favor of #1268 !

**Pull request closed without merging**
