### PR TITLE
Test coverage

### PR DESCRIPTION
**Pull request by jmcarp**
TBD: upload coverage reports to a service like code climate or codecov and warn on patches that decrease coverage. Any preferences on a code coverage service @schuyler1d @shakalee14 ?

### CODE REVIEW

**Comment by shakalee14** [comment]
i have no preference @jmcarp - how about you @schuyler1d , @hiemanshu ?

**Comment by schuyler1d** [comment]
I don't have a preference.  My main request is we use one that isn't overly 'chatty'.  e.g. coveralls.io seems to message 4 times per PR (or did/sometimes does): https://github.com/hdachev/fakeredis/pull/60

**Comment by jmcarp** [comment]
Updated to push coverage reports to code climate: https://codeclimate.com/github/jmcarp/Spoke. To get this working on upstream, we'll need to sign up for code climate (free for open source), add this repo, and use `travis encrypt` to add the code climate api key to the travis config. Happy to pair on this if helpful.

**Comment by jmcarp** [comment]
This is ready for review, so I'm dropping the `WIP` label.

**Review by shakalee14 — APPROVED** [review]

**Pull request merged**
