### PR TITLE
People pagination

### PR DESCRIPTION
**Pull request by shakalee14**

### CODE REVIEW

**Comment by shakalee14** [comment]
Hey @schuyler1d - i get the following error when running this locally after trying to create a new campaign (http://localhost:3000/admin/orgid/campaigns/campaignid/edit?new=true)

```
11:46:33 AM server.1              |  error: syntax error at or near "as"
11:46:33 AM server.1              |      at Connection.parseE (/Users/shaka/moveon/Spoke/node_modules/pg/lib/connection.js:567:11)
11:46:33 AM server.1              |      at Connection.parseMessage (/Users/shaka/moveon/Spoke/node_modules/pg/lib/connection.js:391:17)
11:46:33 AM server.1              |      at Socket.<anonymous> (/Users/shaka/moveon/Spoke/node_modules/pg/lib/connection.js:129:22)
11:46:33 AM server.1              |      at emitOne (events.js:96:13)
11:46:33 AM server.1              |      at Socket.emit (events.js:188:7)
11:46:33 AM server.1              |      at readableAddChunk (_stream_readable.js:176:18)
11:46:33 AM server.1              |      at Socket.Readable.push (_stream_readable.js:134:10)
11:46:33 AM server.1              |      at TCP.onread (net.js:547:20)
```

**Comment by joemcl** [comment]
hey @schuyler1d by 'wait for a knex upgrade' above - do you mean an upgrade of the version that can be installed with Spoke, because of other dependencies, or something else, like a version of knex that's still in development in that project?

**Comment by schuyler1d** [comment]
> hey @schuyler1d by 'wait for a knex upgrade' above - do you mean an upgrade of the version that can be installed with Spoke, because of other dependencies, or something else, like a version of knex that's still in development in that project?

I haven't looked, but considering the original syntax was documented at knexjs.org, I assume a more up-to-date version supports the original syntax.  I don't think the sorting feature is important enough to hold this back though (or even bother investigating when/if knex fixed/improved this).

**Comment by schuyler1d** [comment]
fwiw, I think this might be ready for stage now

**Comment by joemcl** [comment]
Thanks @schuyler1d got it and agree should not hold it back, but definitely sorting useful to implement down the road.

**Comment by schuyler1d** [comment]
Ah, @joemcl to be clear, the current PR still sorts -- first by first name, then by last name, and then by ID.  The previous one just sorted id last in descending order (so recents were first) -- now it will sort with oldest first (if first AND last names are the same).  That actually seems fine to me -- the expressed use case is finding someone quickly when you know their name vs. an ability to see the most recent creations at the top.

**Comment by joemcl** [comment]
OK great @schuyler1d and I think @suegibson @deasterdaywfp and other folks will like it, sounds much better than current People.

**Comment by deasterdaywfp** [comment]
Sounds great! Thanks for the work on this @schuyler1d and @shakalee14 !

**Comment by ibrand** [comment]
@shakalee14 and @schuyler1d this is now a pretty old PR with a few merge conflicts on it. I can't quite tell if it's been addressed since in #1131. Has it been? Should I close this?

**Comment by shakalee14** [comment]
Fine to close for now - I believe we're implementing this different re: @lperson work.

**Comment by schuyler1d** [comment]
closing

**Pull request closed without merging**
