### PR TITLE
Add comment reminding us to reevaluate optimization of interaction steps loading after react >=16 upgrade 

### LINKED ISSUE #1335: Improve performance of interaction steps editor
As part of RFC #1320 and the project [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14), merge the work in these WorkingFamiles/Spoke PRs:
- [122](https://github.com/WorkingFamilies/Spoke/pull/122) 
- [124](https://github.com/WorkingFamilies/Spoke/pull/124)  

See **_[MoveOn PR 1179](https://github.com/MoveOnOrg/Spoke/pull/1179)_**

### PR DESCRIPTION
**Pull request by lperson**
# Fixes #1335 

## Description

Add comment reminding us to reevaluate optimization of interaction steps loading after react >=16 upgrade.  This addresses a [comment](https://github.com/MoveOnOrg/Spoke/pull/1179#discussion_r361673366) in #1179 

# Checklist:

- [ ] ~I have manually tested my changes on desktop and mobile~
- [x] The test suite passes locally with my changes
- [ ] ~If my change is a UI change, I have attached a screenshot to the description section of this pull request~
- [x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] ~I have made any necessary changes to the documentation~
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [ ] ~My PR is labeled [WIP] if it is in progress~

### CODE REVIEW

**Comment by ibrand** [comment]
@lperson This is a giant diff for a comment. Is that because it's a diff of main and the original PR isn't merged yet?

**Comment by lperson** [comment]
> @lperson This is a giant diff for a comment. Is that because it's a diff of main and the original PR isn't merged yet?

~~Ugh.  Yes.  Although it doesn't merge cleanly.  💥~~

My final answer is yes.  I'll merge main.

**Comment by lperson** [comment]
Because life is short, I reset the branch to moveon/main and applied the one line change.

Thanks for flagging this @ibrand

**Review by ibrand — APPROVED** [review]
🎉

**Pull request merged**
