### PR TITLE
On Lambda, await action handler methods to avoid API calls timing out + refactoring and tests for onTagUpdate

### PR DESCRIPTION
**Pull request by lperson**
Lambda teardown was probably causing fire and forget API calls to
timeout.

This was noticed by an organization using the VAN integration. About half the calls to the VAN API timed out, and we weren't awaiting the result. They're going to install this branch and we'll see if it solves that problem.

Also, since this change touched the call to `onUpdateTags` I included some refactoring around that in `updateContactTags` and a unit test for `updateContactTags`.

# Fixes # (issue)

## Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change, and any blockers that make your change a WIP_

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by schuyler1d** [comment]
This is something I'd like to fold into @matteosb 's dispatching framework (where these are dispatched, along with e.g. sends, etc) but agree this is a good interim solution.

**Comment by schuyler1d** [comment]
changed base in preparation for 7.0 merge/release

**Comment by matteosb** [comment]
@schuyler1d and @lperson, can we close this PR now that the task dispatching framework has been merged? In Lambda you can now pass TASKS_SYNC to await the call to the action handler or use the lambda-async job runner (recommended). Is there anything in here that should be carried over?

**Comment by lperson** [comment]
> @schuyler1d and @lperson, can we close this PR now that the task dispatching framework has been merged? In Lambda you can now pass TASKS_SYNC to await the call to the action handler or use the lambda-async job runner (recommended). Is there anything in here that should be carried over?

Nope!

**Comment by lperson** [comment]
🎉

**Pull request closed without merging**
