### PR TITLE
Connect to postgresql in SSL mode

### PR DESCRIPTION
**Pull request by hiemanshu**
Use SSL for postgres when required.

### CODE REVIEW

**Review by shakalee14 — APPROVED** [review]

**Comment by sandramchung** [comment]
Let's also add the new DB_USE_SSL variable to the .env.example template.

**Comment by hiemanshu** [comment]
I've updated the commit, and added the new env variable to the env template, and config template

**Review by sandramchung — APPROVED** [review]
LGTM

**Comment by sreynen** [comment]
Tested and confirmed this doesn't break anything.

**Pull request merged**
