### PR TITLE
Message Review: clear selections after reassigning texters

### LINKED ISSUE #1023: Marking conversations for reassigning
I appreciate this feature, but after reassigning the conversations, the check marks don’t disappear. They attach themselves to the subsequent conversations in the list. When I scroll to another page of conversations, the check marks will be there, too, uninvited. Unticking all the boxes takes up more of my time and is annoying. 
@bdatkins @lperson @joemcl

### PR DESCRIPTION
**Pull request by lperson**
Closes #1023

### CODE REVIEW

**Comment by shakalee14** [comment]
Hey @lperson - can you resolve the conflicts so I can get this branch into our staging branch and through QA? Thanks in advance!

**Review by schuyler1d — APPROVED** [review]
:+1: 
need to fix merge conflicts, but otherwise, great!

**Comment by lperson** [comment]
@schuyler1d @shakalee14 merge conflicts resolved

**Comment by joemcl** [comment]
hey @lperson FYI this looks to me like it's working as desired on our staging site, but I'd like @suegibson to test it out as well, on her iPad. Thanks!

**Comment by suegibson** [comment]
This is about the check marks, right? Am I supposed to see the change already?
Yeah. Just tried it. They did disappear after reassigning. Thanks, everyone!

**Pull request merged**
