### PR TITLE
Issue 1113: First and last name should be required in auth0 login page

### PR DESCRIPTION
**Pull request by cgalbiati**
https://github.com/MoveOnOrg/Spoke/issues/1113

### CODE REVIEW

**Comment by joemcl** [comment]
thanks @cgalbiati and my Issue title was not clear - First Name and Last Name were not showing *at all* as fields in the Sign Up link, much less as required. I figured out that problem, the fix is in the Issue comments in #1113 .  If this now makes sure those are required, all the better, and thank you.

**Comment by ibrand** [comment]
Hey @cgalbiati! I'm noticing that the issue itself here was resolved, but seems like your PR adds validation that wasn't previously there to ensure that there actually *is* a first and last name. Is that correct? If so, we should merge this regardless of its connection to #1113

**Comment by ibrand** [comment]
@cgalbiati wanted to ping you again on this one cause I'd love to merge it if it's still relevant :)

**Comment by cgalbiati** [comment]
@ibrand My PR does add extra validation, so if that is desired, then it should be merged.  I don't actually have access to do so, so someone else will have to.

**Comment by ibrand** [comment]
@cgalbiati thank you so much for your work on this. Sounds like the team discussed and validation isn't needed here after all so I'm going to close the PR. That said, I really appreciate you jumping in and submitting a PR!

**Pull request closed without merging**
