### PR TITLE
import interactions and canned responses from a google doc

### LINKED ISSUE #1102: Add ability to load/import a script from Google doc, other external source
It would be really handy to be able to load or import a Campaign 'script'/Interactions and Canned from an external source, particularly a Google Drive doc, which is what we use for templates and draft scripts. That way a collaborator can help edit/tweak a script and once finalized a user with Spoke Admin rights can import it right into a new campaign. It would also eliminate the tedium and time-waste of copying and pasting Interactions and Canned from a Google Doc into the Campaign creation UI.

### PR DESCRIPTION
**Pull request by lperson**
closes #1102 

This is something @joemcl, @suegibson and @deasterdaywfp will find useful.

This PR requires node 10.  I created #1117 to isolate the changes for node 10, which are also included in this branch.

### CODE REVIEW

**Comment by deasterdaywfp** [comment]
Thank you hero @lperson!

**Comment by joemcl** [comment]
thanks @lperson gonna test it on staging today, deploying your branch..

**Comment by shakalee14** [comment]
hey @lperson - can you investigate why tests are failing for this pr?

**Comment by lperson** [comment]
> hey @lperson - can you investigate why tests are failing for this pr?

@shakalee14 I propose that [PR 1134 (merge WFP/staging_20190601 into moveon/main)](https://github.com/MoveOnOrg/Spoke/pull/1134) supersede this one.  It is a superset.  I'll make sure tests pass for 1134.

**Comment by joemcl** [comment]
hey @ibrand @schuyler1d @shakalee14 what's the status on this? Thanks.

**Comment by shakalee14** [comment]
Merged with https://github.com/MoveOnOrg/Spoke/pull/1134/files

**Pull request closed without merging**
