### PR TITLE
Select multiple campaigns in message review

### LINKED ISSUE #1322: Select multiple campaigns in message review
As part of RFC #1320 and the project [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14), merge the work in these WorkingFamiles/Spoke PRs:
- [96](https://github.com/WorkingFamilies/Spoke/pull/96) 
- [97]( https://github.com/WorkingFamilies/Spoke/pull/97) 
- [113](https://github.com/WorkingFamilies/Spoke/pull/113)

### PR DESCRIPTION
**Pull request by lperson**
# Fixes #1322 

## Description

Allow a user to specify multiple campaigns in message review.

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes
- [x] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
-  ~I have made any necessary changes to the documentation~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~My PR is labeled [WIP] if it is in progress~

### CODE REVIEW

**Comment by joemcl** [comment]
Thanks @lperson and hi @ibrand . So @ibrand can you create a test deployment site for this as you did for #1308 ?

**Comment by joemcl** [comment]
hey @lperson @ibrand sorry for the delay on this. thanks for the test deploy. I used that, created a user , an org, two test campaigns with test contacts. I'm just getting spinning then it stops when in Message Review -> Message Filter -> Select a campaign. Also 'sent' some texts - which don't actually go out right @ibrand - and nothing comes up in Message Review when selecting All in Message Status.

**Review by joemcl — COMMENTED** [review]
hey @lperson @ibrand sorry for the delay on this. thanks for the test deploy. I used that, created a user , an org, two test campaigns with test contacts. I'm just getting spinning then it stops when in Message Review -> Message Filter -> Select a campaign. Also 'sent' some texts - which don't actually go out right @ibrand - and nothing comes up in Message Review when selecting All in Message Status.

**Comment by ibrand** [comment]
Yep @joemcl ! Those texts don't go out, and you wont get replies either

**Comment by joemcl** [comment]
> Yep @joemcl ! Those texts don't go out, and you wont get replies either

Cool just making sure

**Review by schuyler1d — APPROVED** [review]
nit: ideally remove the added `console.log()`

**Comment by ibrand** [comment]
**Ignore this comment. I experimented with merging main into this branch since a bunch of changes have happened there since this PR, and it worked great :)**

<hr/>

@lperson when I try `yarn dev` on this PR branch I see

```
12:46:53 PM server.1 |  CREATING DATABASE SCHEMA
12:46:53 PM server.1 |  migration file "20191108164924_message_errors.js" failed
12:46:53 PM server.1 |  migration failed with error: drop index `message_user_number_index` - SQLITE_ERROR: no such index: message_user_number_index
12:46:54 PM server.1 |  Unhandled rejection Error: SQLITE_ERROR: no such index: message_user_number_index
12:46:54 PM server.1 |      at Client_SQLite3._query (/Users/ilonabrand/web/Spoke/node_modules/knex/lib/dialects/sqlite3/index.js:110:12)
12:46:54 PM server.1 |      at Client_SQLite3.query (/Users/ilonabrand/web/Spoke/node_modules/knex/lib/client.js:192:17)
12:46:54 PM server.1 |      at /Users/ilonabrand/web/Spoke/node_modules/knex/lib/transaction.js:255:21
```

Admittedly, I've been seeing a lot of sqlite problems today, but i'm curious if this is a flag for something wrong with this PR.

**Comment by lperson** [comment]
@ibrand do you get the same thing in moveon/main?

**Comment by lperson** [comment]
Also, I just merged moveon/main into this branch.  Maybe try again?

**Comment by lperson** [comment]
@ibrand I couldn't reproduce this locally.  Would you let me know if the branch with main merged into it still has the same issue?

**Comment by ibrand** [comment]
Yep @lperson that's why I wrote
> Ignore this comment. I experimented with merging main into this branch since a bunch of changes have happened there since this PR, and it worked great :)

I went ahead and merged main in and it fixed it. Sorry for the confusion! I have this as part of 5.2 which we'll roll out soon

**Comment by lperson** [comment]
@ibrand I missed that 😊

**Comment by ibrand** [comment]
This got merged in with v5.2

**Pull request closed without merging**
