### PR TITLE
Stage main

### PR DESCRIPTION
**Pull request by ibrand**
**@schuyler1d**
#1130 
#1154 

**@azuzunaga**
#1074 

**@shakalee14**
#1180

### CODE REVIEW

**Comment by shakalee14** [comment]
@ibrand - is this ready to test on stage?

**Review by schuyler1d — DISMISSED** [review]
:+1:

**Comment by ibrand** [comment]
It is ready to test on stage!

**Comment by shakalee14** [comment]
Receiving a 
```
"client debug 
{…}
message: "id is not defined"
status: 500"
```
and `ReferenceError: id is not defined` at `Spoke/src/server/api/schema.js:671:38`
when attempting to archive multiple campaigns

**Review by shakalee14 — APPROVED** [review]

**Pull request merged**
