### PR TITLE
updating disabled color to faded white

### PR DESCRIPTION
**Pull request by nkartha2**
# Fixes # (issue)
https://github.com/MoveOnOrg/Spoke/issues/1740

## Description
- This is my first PR for the Spoke project!
- I changed the inactive color of the arrow buttons to faded white instead of faded gray as requested in the above issue
- Screenshot of the fix: 
Screen Shot 2020-09-22 at 8 39 57 PM

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [] The test suite passes locally with my changes
- [x] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [x ] [My change is 300 lines of code or less]

- [ ] I have made any necessary changes to the documentation
- unsure about where to update this

- [ ] I have added tests that prove my fix is effective or that my feature works
are there any tests for UI changes?

- [x] My PR is labeled [WIP] if it is in progress
- not WIP

### CODE REVIEW

**Review by schuyler1d — DISMISSED** [review]
:+1:

**Comment by schuyler1d** [comment]
Hm, so the problem with this is that the disabledColor is also the unfocused text-field placeholder text and that field bg is white, and so making this disabledColor faded white makes the placeholder (field name) invisible.

**Comment by nkartha2** [comment]
@schuyler1d ah ok. let me take a look this weekend if can handle the different states better.

**Comment by nkartha2** [comment]
Disabled arrow colors updated without impacting the inputs elsewhere. 

Screen Shot 2021-01-25 at 11 22 30 PM
Screen Shot 2021-01-25 at 11 22 47 PM

**Comment by schuyler1d** [comment]
this was merged in v11.0!

**Pull request closed without merging**
