### PR TITLE
Change License to GPL3 with an additional term

### PR DESCRIPTION
**Pull request by schuyler1d**
Additional term using GPL3 Section 7(b) author attribution to preserve author attributions in the application UI where it says:
> Spoke is developed and maintained by people committed to fighting oppressive systems and structures, including economic injustice, racism, patriarchy, and militarism

attribution-anonymous

### CODE REVIEW

**Review by ibrand — APPROVED** [review]
🥳

**Comment by tmc** [comment]
Added some comments/questions in slack.

**Comment by tmc** [comment]
Specifically, does the consent of past contributors need to be sought? If not legally necessary, should it be sought?

**Comment by tmc** [comment]
Can we get in the TexterFAQ/UserEdit attribution change (which I 100% support) in now and discuss the license change separately (which I am less sure about)?

**Comment by tmc** [comment]
> Can we get in the TexterFAQ/UserEdit attribution change (which I 100% support) in now and discuss the license change separately (which I am less sure about)?

@schuyler1d and I had a chance to catch up and I'm supportive of the license change.

**Pull request merged**
