### PR TITLE
Update org join link text

### PR DESCRIPTION
**Pull request by joemcl**
Changed line 19 from
`Send your texting volunteers this link! Once they sign up, they'll be automatically assigned to this campaign.
`
to
`Send your texting volunteers this link! Once they sign up, they'll be automatically assigned to this Organization.
`

### CODE REVIEW

**Comment by joemcl** [comment]
Aargh. I'm trying to change the text that appears in the big green and white join + icon in People - at https://[Spoke website]/admin/1/people 
not the text that appears in a Campaign under Texters (the dynamic join link), for example in
https://[Spoke website]/admin/1/campaigns/934/edit

**Comment by ibrand** [comment]
Hey @joemcl, I'm not sure of the status of this PR. Is there an issue open describing the text issue you were trying to work with here?

**Comment by joemcl** [comment]
@ibrand just added Issue #1218

**Comment by schuyler1d** [comment]
This was fixed with https://github.com/MoveOnOrg/Spoke/pull/1226

**Comment by joemcl** [comment]
@schuyler1d not sure it was fixed actually - I wrote this comment about that PR -  
"OK but - I believe a Spoke instance has to have at least one Organization by default - and the join link is in People, not per (Spoke) Campaign. Alternating that text between 'organization or campaign' is confusing. So how about this @schuyler1d @ibrand @WSINTRA - rather than 'organization', the link text populates with whatever the actual name of the Organization is that was created on first deploy - so it could be Joe Blow for City Council Campaign, People for Action Organization, whatever."

**Pull request closed without merging**
