### PR TITLE
1591: Remove Opt outs menu 

### PR DESCRIPTION
**Pull request by bdatkins**
# Fixes # 1591

## Description

Removal of the Admin Opt out side menu item and cleanup of corresponding page.
(Recreated PR bc there was co-mingling of commits/issues.)

# Checklist:

- [X] I have manually tested my changes on desktop and mobile
- [X] The test suite passes locally with my changes
- [X] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [X] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [X] I have made any necessary changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] My PR is labeled [WIP] if it is in progress

89246755-d7997780-d5d9-11ea-9ff7-d4a11fbf1380

### CODE REVIEW

**Comment by bdatkins** [comment]
@ibrand Recreated this PR, please re-review

**Review by schuyler1d — APPROVED** [review]
I want to keep the component and the path and just remove the menu item, so I cherry-picked it here:
https://github.com/MoveOnOrg/Spoke/commit/0c58ac5e888257f143ee3e6bb33504d89ed535cc

I'm going to close this PR after that merges.
Thank you!

**Comment by bdatkins** [comment]
Totally fine with me @schuyler1d , thanks!

**Comment by schuyler1d** [comment]
Closing -- this was merged in 8.1/9.0 release.

**Pull request closed without merging**
