### PR TITLE
adds keyboard navigation to texter view

### LINKED ISSUE #1400: Feature Request: Keyboard Shortcut: "<" and ">" controlled via left + right arrow keys
**Problem**
repetitive mouse movements = pain + inefficiency

**Rx**
Keyboard Shortcuts!!
In the responding flow, map the left and right arrow keys to the previous and next arrow buttons.

**Scenario**
In many flows, responding to people who have replied "Yes" is very time sensitive. Texters will often request a very large assignment, then triage the replies and respond to the "Yes" replies first. Currently, this is done by arrowing through the replies and responding to any "Yes" replies. If the arrow keys were mapped to the previous and next actions it would make this smoother and require less mouse-ing/trackpad-ing. 

**Keyboard Shortcut Guide**

https://www.figma.com/file/OTyLXArAcIKCZNl7Z0Dxc9/Spoke-KeyboardShortcuts?node-id=0%3A1

image

### PR DESCRIPTION
**Pull request by tom-raley**
# Fixes #1400 

## Description

Adds keyboard arrow navigation to tab through contacts using the left and right arrow keys

# Checklist:

- [x ] I have manually tested my changes on desktop and mobile
- [ x] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [x] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by ibrand** [comment]
Hey @tom-raley thanks for the PR! I'm noticing the [tests failing](https://travis-ci.org/github/MoveOnOrg/Spoke/builds/660130279#L16977) because of the usage of `document.addEventListener`. I'm noticing from some cursory [googling](https://stackoverflow.com/questions/39310754/react-addeventlistener-is-not-a-function-error) that React has problems with `document.addEventListener`

We're gonna need to change that syntax for this to pass.

**Comment by tom-raley** [comment]
Hey @ibrand! Thanks for following up, I did notice that test was failing, I assumed it was because the document wasn't being mocked. I can't find another way to do this without using document, window or using refs which aren't supported in the version of React being used. If anyone else has a hint that would super helpful!

**Comment by schuyler1d** [comment]
I think we should discuss the issue a bit more -- I'm a little concerned for accidental navigation.  Some use-cases:
* Right now, this would trigger even if I use the arrow keys while editing a message (or an opt-out message) [this could be fixed with some code work]
* I might accidentally hit left/right when aiming to scroll up/down on the message thread -- currently, if I navigate left/right I lose whatever message/question choice I had been editing, so maybe before we work on this, we should make sure that edit state survives navigation back-and-forth?

**Comment by ibrand** [comment]
There is a WIP PR open for this, but this is available if someone wants to pick up on where the PR leaves off and also address the feedback around accidental navigation

**Comment by schuyler1d** [comment]
How about the `Crl-<comma>` (i.e. "<" key) and `Ctrl-<period>` (i.e. ">" key).

**Comment by deasterdaywfp** [comment]
@schuyler1d I would support that - also want to note this issue as one connected to a desire for this functionality in Message Review to tab through conversation review.

**Comment by deasterdaywfp** [comment]
support this!

**Pull request closed without merging**
