### PR TITLE
Docsify

### LINKED ISSUE #1605: Feature Request: Consider publishing ~/docs using GitHub Pages and/or readthedocs.org
**Problem**
The /docs are not easily accessible to folks who are unfamiliar with GitHub
 
**Solution**
Publish [~/docs](https://github.com/MoveOnOrg/Spoke/tree/main/docs) using [GitHub Pages](https://help.github.com/en/github/working-with-github-pages) and/or [readthedocs.org](readthedocs.org)

**Context**

### PR DESCRIPTION
**Pull request by ibrand**
# Fixes #1605

## Description
Use docsify as mentioned in #1701 to create a doc microsite for Spoke. This is a first pass basically sorting all of the docs that we have as of right now into headings. I'd love to consider making some folders in the docs repo and adding more docs, but this is a reasonable place to start.

### Screenshot
Screen Shot 2020-08-19 at 5 32 42 PM

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes
- [x] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [x] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by sharonsolomon** [comment]
@ibrand Is it possible to include the documents in the main folder? I.e. Contributing and Community Guidelines

**Review by schuyler1d — APPROVED** [review]
Awesome!!!

**Comment by ibrand** [comment]
@sharonsolomon Frustratingly, this microsite is scoped to the docs/ folder. I think there is a workaround I could do here to fix that though and the fact that you're bringing it up makes me want to further investigate. I'll do a follow up PR!

**Comment by arena** [comment]
The screenshot and the table of contents look great!

**Review by arena — APPROVED** [review]
👍

**Comment by ibrand** [comment]
@arena at some point, this is totally a place where we could have a header called "design briefs" or something like that

**Pull request merged**
