### PR TITLE
Starting Doc 

### PR DESCRIPTION
**Pull request by MichaelEWalker87**
## Description

This is to supply a quick setup guide for setting up the devolvement environment with SQLite. This includes adding additional steps for those that never used Github workflows, providing pictures and Terminal commands needed to get the application up and running.   

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes (no test needed)
- [x] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [x] I have made any necessary changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Review by crayolakat — CHANGES_REQUESTED** [review]
Thanks for the contributions to Spoke documentation! Much of the content in this file looks similar to what's in here: https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO_DEVELOPMENT_LOCAL_SETUP.md

Instead of creating a file, can you edit `docs/HOWTO_DEVELOPMENT_LOCAL_SETUP.md` to add your changes there?

**Comment by MichaelEWalker87** [comment]
@crayolakat @Arique1104 

I used the base of the previous getting started [Doc](https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO_DEVELOPMENT_LOCAL_SETUP.md) to make this SQlight Doc. I do not have the space on this machine to test the Docker and Postgres and verify if I am leaving bad information in the document if I combine the two documents. I can combine the two but would need help verifying that the steps taken in Docker and Postgres are correct and preferably adding more images/details to help ease confusion when onboarding.  

Please advise

**Comment by MichaelEWalker87** [comment]
@crayolakat @Arique1104

Thank You Arique for helping to get the images on the Docker section 

while with Arique we pulled some info from HOWTO_USE_POSTGRESQL.md

Also added images to help with setup in the section Your Database

If you both would be able to take a look and make sure I did not make any errors or need to add any additional images as mentioned previously I am not sure about Postgres setup or Docker 

I also have not taken the steps to check beyond step 3 in "Getting the app running"  so I might need some verification that the process works

**Review by ibrand — COMMENTED** [review]
I'm going to choose not to merge this in, and was originally going change by change with feedback but I'm instead going to explain why here.

The additions here roughly fell into 3 categories and for each category I can highlight why I'm opting to keep the README the same:
**1. Adding screenshots to processes**
Screenshots take up a lot of space, and don't provide us with information that we can't already glean by checking our work. For example, a screenshot of the output of `nvm use` will reveal the same thing that running it will unless there's an error. If there's an error, that should flag that something went wrong. Additionally, screenshots of things like `.env` files can become out of date pretty quickly and people wont think to update that screenshot.

**2. Github, command-line, or vscode specific instructions that were more about understanding those tools than setting up Spoke**
It is important that we make things clear regarding our tooling and don't expect that people know it coming in. That said, the README for Spoke isn't the place for people to learn about vscode features or how to clone a repo from github. The goal of our README is to give you all the tools you need to set up Spoke specifically assuming you already know how github and javascript work.

**3. A Fixes and Updates section**
This was an interesting idea. We actually already have a [release notes](https://github.com/MoveOnOrg/Spoke/blob/main/docs/RELEASE_NOTES.md) file set up to fill the function that you were trying to solve for. Generally a combination of the release notes, [issues](https://github.com/MoveOnOrg/Spoke/issues), and [open pull requests](https://github.com/MoveOnOrg/Spoke/pulls) should be enough to help people access this type of information.

Broadly, we want our README to be as clear and concise as possible while allowing for devs from a wide range of experience to be able to use it. We also want to not have things in here that change regularly (like screenshots of `.env` which can easily change with a feature update.)

Thank you for working through this. What I do see in this PR is a lot of good learning and building an understanding of how to set up a Spoke environment 🎉

**Pull request closed without merging**
