### PR TITLE
#1502: Maked canned responses editable 

### PR DESCRIPTION
**Pull request by aschneit**
# Fixes # (issue)
#1502

## Description

Added an editing icon and extended the create canned response modal to be reused for editing. 

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes
- [x] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [x] I have made any necessary changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] My PR is labeled [WIP] if it is in progress

Screen Shot 2020-05-27 at 2 31 41 PM

### CODE REVIEW

**Comment by schuyler1d** [comment]
What's the status of this?  Is it still WIP?  Would love to get this in, in the next version.

**Comment by joemcl** [comment]
By 'editable' you mean after a campaign has been launched?

**Review by schuyler1d — DISMISSED** [review]
:+1: 
and yei tetss!

**Comment by schuyler1d** [comment]
this was merged in 7.1

**Pull request closed without merging**
