### PR TITLE
fix message sending where additional context info needs to be sent fo…

### PR DESCRIPTION
**Pull request by schuyler1d**
…r service.sendMessage than previously -- e.g. for TWILIO auth, etc

# Fixes # (issue)

## Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change, and any blockers that make your change a WIP_

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Review by lperson — DISMISSED** [review]

**Comment by mayefsky** [comment]
Next step is for me to test this? Or do you want to merge it first.

**Comment by schuyler1d** [comment]
@bobbyoderek please test it first -- we merge PRs in release batches and very rarely will merge PRs individually.

**Comment by mayefsky** [comment]
OK sounds good--I have it running (merged with my own branch that includes the script to actually run the erroredMessageSender) as a cron; I don't know of an easy way to force a -1 to occur in my own account but given regular usage expect there will be at least a couple of naturally occurring ones tonight.

Relatedly but separately, what is the expected behavior as far as reporting when a retry is successful? Should I expect admins to still see the -1 errors in their reports, or do the error codes for those messages get erased?

**Comment by mayefsky** [comment]
OK--as far as testing on real errored messages, this seems to work, but with 2 big caveats (see output below with phone number and sensitive keys redacted:

1) This seems to dump the contents of the Org's features into the logs. Since some sensitive per-org campaign features are stored in the DB in the clear (e.g. VAN keys), that seems not ideal. I don't see this in my logs for the regular running service, so not sure why it happens here.

2)I'm not sure why we get another backend info Sending (twilio):  -> +[REDACTED] 2 minutes after the first; more generally, I'm not sure how to manage this as a cron timing-wise, and/or what logging we expect to go to the cron process vs. the main process, but I think that's not directly related to this so will ask in slack.


```
Aug 17 08:45:30 PM  Kicking off an errored message resend run
Aug 17 08:45:30 PM  Running a message sender
Aug 17 08:45:30 PM  Finishing up an errored message resend run
Aug 17 08:45:31 PM  backend info Sending (twilio):  -> +[REDACTED]
Aug 17 08:45:31 PM  Message: Terrific. Can Joe Kennedy count on your support in the Democratic primary?
Aug 17 08:45:32 PM  twilioMessage { to: '[REDACTED]',
Aug 17 08:45:32 PM    body:
Aug 17 08:45:32 PM     'Terrific. Can Joe Kennedy count on your support in the Democratic primary?',
Aug 17 08:45:32 PM    messagingServiceSid: 'MGb615f0491401a379bb13dd21a45e78a8',
Aug 17 08:45:32 PM    statusCallback: undefined }
Aug 17 08:45:33 PM  backend info postMessageSend anonymous {
Aug 17 08:45:33 PM    id: 406011,
Aug 17 08:45:33 PM    user_number: '',
Aug 17 08:45:33 PM    user_id: 193,
Aug 17 08:45:33 PM    contact_number: '[REDACTED]',
Aug 17 08:45:33 PM    is_from_contact: false,
Aug 17 08:45:33 PM    text:
Aug 17 08:45:33 PM     'Terrific. Can Joe Kennedy count on your support in the Democratic primary?',
Aug 17 08:45:33 PM    assignment_id: null,
Aug 17 08:45:33 PM    service: 'twilio',
Aug 17 08:45:33 PM    service_id: '',
Aug 17 08:45:33 PM    send_status: 'SENDING',
Aug 17 08:45:33 PM    created_at: 2020-08-18T00:25:38.281Z,
Aug 17 08:45:33 PM    queued_at: 2020-08-18T00:25:38.281Z,
Aug 17 08:45:33 PM    sent_at: 2020-08-18T00:25:38.280Z,
Aug 17 08:45:33 PM    service_response_at: 2020-08-18T00:25:38.280Z,
Aug 17 08:45:33 PM    send_before: null,
Aug 17 08:45:33 PM    error_code: -1,
Aug 17 08:45:33 PM    campaign_contact_id: 603919,
Aug 17 08:45:33 PM    messageservice_sid: 'MGb615f0491401a379bb13dd21a45e78a8',
Aug 17 08:45:33 PM    campaign_id: 322,
Aug 17 08:45:33 PM    message_status: 'convo',
Aug 17 08:45:33 PM    organization_id: 4,
Aug 17 08:45:33 PM    features:
Aug 17 08:45:33 PM     '{REDACTED BUT THIS INCLUDES MY TWILIO KEYS (WHICH ARE ENCRYPTED) AND MY VAN API KEY (NOT ENCRYPTED!) } { body:
Aug 17 08:45:33 PM     'Terrific. Can Joe Kennedy count on your support in the Democratic primary?',
Aug 17 08:45:33 PM    numSegments: '0',
Aug 17 08:45:33 PM    direction: 'outbound-api',
Aug 17 08:45:33 PM    from: null,
Aug 17 08:45:33 PM    to: '[redacted]',
Aug 17 08:45:33 PM    dateUpdated: 2020-08-18T00:45:32.000Z,
Aug 17 08:45:33 PM    price: null,
Aug 17 08:45:33 PM    errorMessage: null,
Aug 17 08:45:33 PM    uri:
Aug 17 08:45:33 PM     '/2010-04-01/Accounts/AC4e68438e2a47eae26bb3b94b9109507f/Messages/SMe6ff1f5ed93847399522f9d231e81ea1.json',
Aug 17 08:45:33 PM    accountSid: 'AC4e68438e2a47eae26bb3b94b9109507f',
Aug 17 08:45:33 PM    numMedia: '0',
Aug 17 08:45:33 PM    status: 'accepted',
Aug 17 08:45:33 PM    messagingServiceSid: 'MGb615f0491401a379bb13dd21a45e78a8',
Aug 17 08:45:33 PM    sid: 'SMe6ff1f5ed93847399522f9d231e81ea1',
Aug 17 08:45:33 PM    dateSent: null,
Aug 17 08:45:33 PM    dateCreated: 2020-08-18T00:45:32.000Z,
Aug 17 08:45:33 PM    errorCode: null,
Aug 17 08:45:33 PM    priceUnit: null,
Aug 17 08:45:33 PM    apiVersion: '2010-04-01',
Aug 17 08:45:33 PM    subresourceUris:
Aug 17 08:45:33 PM     { media:
Aug 17 08:45:33 PM        '/2010-04-01/Accounts/AC4e68438e2a47eae26bb3b94b9109507f/Messages/SMe6ff1f5ed93847399522f9d231e81ea1/Media.json' } } null
Aug 17 08:47:28 PM  backend info Sending (twilio):  -> +[REDACTED]
Aug 17 08:47:28 PM  Message: Terrific. Can Joe Kennedy count on your support in the Democratic primary?
```

**Pull request merged**
