### PR TITLE
Uniform colors and logo

### PR DESCRIPTION
**Pull request by agreenspan24**
## Description

Core background color config gets used in material ui theme and universally applied. User can also set the secondary background color config (default is yellow), which mainly just does backgrounds on the campaign admin page.

IMPORTANT: this does change the text color on the campaign admin page from dark grey to white when on a green background. This is due to the built-in `setContrastingColor` algorithm;

image
image
image
image
image

image

Normally, this page looks like this: 
image

# Checklist:

- [x] I have manually tested my changes on desktop and mobile
- [x] The test suite passes locally with my changes
- [x] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [x] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [x] I have made any necessary changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Review by schuyler1d — DISMISSED** [review]
:+1: woops -- i'll wait until WIP is removed, but this looks good!

**Comment by arena** [comment]
I'd be happy to review this --- is this something I would need to look at locally. Is it even something that is viewable or is it mainly a refactoring that allows customization later?

**Comment by agreenspan24** [comment]
@schuyler1d this is now out of review, only a minor change to fix the issue.

@arena I've added some screenshots, but yes, it allows for customization with this change. Just set CORE_BACKGROUND_COLOR and SECONDARY_BACKGROUND_COLOR environment variables. Let me know if you'd like more visuals.

**Comment by agreenspan24** [comment]
Closing in favor of MUI update and fixes by Stefan

**Pull request closed without merging**
