### PR TITLE
Create a quick link for deploying a production set up to Heroku

### PR DESCRIPTION
**Pull request by ibrand**
# Description
Taking notes from #1452 I've prepped a link for deploying Spoke straight to prod. I've also included a change to app.json that free and paid deploys will need that makes `DB_USE_SSL` true. I think that the new generation of Heroku DBs require SSL connections.

### CODE REVIEW

**Comment by jeffm2001** [comment]
This looks great @ibrand.

One question, is it `DB_USE_SSL` that needs to be set, or `PGSSLMODE`? Just wondering because in HOWTO_HEROKU_DEPLOY.md it references PGSSLMODE. In my deploy I have both set.

My one other flag is in the README, where it says "ballpark for 100k texts" is somewhat vague. Is that intended to mean per month? total? I actually have no idea what the correct answer is, and in reality it's probably more determined by number of simultaneous users rather than number of messages. Perhaps it would be better to say something line "should be suitable for production-level usage for most organizations."

**Comment by jeffm2001** [comment]
Oh, and @schuyler1d, should the `heroku-redis:hobby-dev` add-on be included for the standard (free) Deploy To Heroku button as well?

**Review by schuyler1d — DISMISSED** [review]
:+1:

**Comment by ibrand** [comment]
Gonna answer a few questions here:

> Oh, and @schuyler1d, should the `heroku-redis:hobby-dev` add-on be included for the standard (free) Deploy To Heroku button as well?

I suppose it doesn't matter too much with the free deploy since redis is used for scaling purposes and the free version never needs to be concerned with scale.

> Perhaps it would be better to say something line "should be suitable for production-level usage for most organizations."

I agree! I'll change that now.

> One question, is it DB_USE_SSL that needs to be set, or PGSSLMODE?

From my testing, it needs to be `DB_USE_SSL` and [this piece of code](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/knex-connect.js#L25-L26) confirms that that's the right variable. When searching the entire codebase I only see `PGSSLMODE` referenced in docs. I'm pretty sure that indicates that it's either since been deprecated or was never the right var and that I should edit it out of the docs in a PR too.

**Review by schuyler1d — APPROVED** [review]
:+1:

**Comment by jeffm2001** [comment]
Looks good!

**Pull request merged**
