### PR TITLE
NPM Security Audit

### PR DESCRIPTION
**Pull request by bchrobot**
Security updates based on `npm audit`

**Major Version Bumps**

* [x] `twilio` - our use of the client is up to date:
    * [`availablePhoneNumbers` and `incomingPhoneNumbers`](https://www.twilio.com/docs/phone-numbers/api/available-phone-numbers)
    * [`messages.create`](https://www.twilio.com/docs/sms/send-messages)
* [x] `foreman` - no breaking changes with version bump
* [x] `sqlite3` - there don't appear to be any breaking API [changes](https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md)
    * Despite that, this may still require `knex@^0.15.0` update in `rethink-knex-adapter` (has [breaking changes](https://github.com/tgriesser/knex/blob/master/CHANGELOG.md))
* [x] `url-parse` (via `react-scripts`) - no breaking changes with version bump
* [x] `hoek` (via `nexmo`) - https://nodesecurity.io/advisories/566
    * Changes to [Nexmo constructor](https://github.com/nexmo/nexmo-node#constructor)
* [x] `debug` (via`rollbar`) - https://nodesecurity.io/advisories/534
    * Changes to [server-side constructor](https://docs.rollbar.com/docs/nodejs#section-standalone)
    * [Changes](https://docs.rollbar.com/docs/browser-js) to browser config `<script>` and global logger name

### CODE REVIEW

**Comment by schuyler1d** [comment]
sqlite3 looks safe looking at the [changelog](https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md)

I don't think we should bump knex on this PR, but we will (and should) in https://github.com/MoveOnOrg/Spoke/pull/692

**Review by schuyler1d — DISMISSED** [review]
:+1:

**Comment by harpojaeger** [comment]
Yeah, #692 gives us `"knex": "^0.15.0"`.

**Comment by shakalee14** [comment]
if we can handle merge conflicts & handle the build error, then we can run this on stage

Currently failing on a react formal import
https://travis-ci.org/MoveOnOrg/Spoke/builds/405926511?utm_source=github_status&utm_medium=notification

**Comment by shakalee14** [comment]
we can wait for those to be included - sorry just noticing the WIP in the title even though this has already been approved.

**Review by schuyler1d — APPROVED** [review]
This looks good
:+1:

**Comment by schuyler1d** [comment]
relevant versions were bumped in v7.0 -- though of course, there are more things to update.

**Pull request closed without merging**
