### PR TITLE
Stage main 2

### PR DESCRIPTION
**Pull request by shakalee14**
@schuyler1d:
#1111 Document Local Login as Default Dev Setup
#1110 Fixes for some texter frontend race conditions

@lperson:
#1107 Sequencing canned response ids
#1112 Message Review board fix

@joemcl:
#1104 Documentation/How to guide for message review board

### CODE REVIEW

**Comment by shakalee14** [comment]
@joemcl

**Comment by joemcl** [comment]
Thanks @shakalee14 will test tonight

**Comment by joemcl** [comment]
OK @shakalee14 so deployed this to our production site, People is back where it was previously, thanks again.

**Comment by schuyler1d** [comment]
@shakalee14 can you merge in locallogin-defaultdev from #1111 again with some additional changes after feedback?

**Review by schuyler1d — APPROVED** [review]
:+1:

**Pull request merged**
