### PR TITLE
Update TEXTER_ACTIVITY_QUERIES.md

### PR DESCRIPTION
**Pull request by Frydafly**
## Description

Added Periscope Dashboard SQL queries for visualizing spoke operations.

# Checklist:

- [ ] I have manually tested my changes on desktop and mobile
- [ ] The test suite passes locally with my changes
- [ ] If my change is a UI change, I have attached a screenshot to the description section of this pull request
- [ ] [My change is 300 lines of code or less](https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md#your-first-code-contribution), or has a documented reason in the description why it’s longer
- [ ] I have made any necessary changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My PR is labeled [WIP] if it is in progress

### CODE REVIEW

**Comment by Frydafly** [comment]
@joemcl not sure what they are called but they are calling filters in my dashboard in periscope. So if you think of the filter name as a placeholder for any values of interest, then it should even work in any basic sql query, so that it’s not specific to periscope.

**Comment by joemcl** [comment]
@Frydafly yeah I just did this on redash.io to test outside of Periscope, and without having to try and dupe the filters on another Periscope instance, and it works:
```
SELECT count(*)
FROM message m
left join campaign_contact n
on m.campaign_contact_id = n.id
left join campaign c
on n.campaign_id = c.ID
left join organization o on o.ID = c.organization_ID
where m.created_at is not null
and o.name is not null
and c.title is not null
and c.title NOT LIKE '%Test%'
and c.title NOT LIKE '%Demo%'
```

**Comment by Frydafly** [comment]
@joemcl Awesome! Let me know if there’s anything I can do to help move this forward and make it usable to folks!

**Comment by joemcl** [comment]
@Frydafly I haven't had time to check out the rest of the queries, and probably won't for a while. If you've used the rest, then I'm sure they work. 

I'd say either:

- explain what you mean by 'Periscope', now known as ["Sisense for Cloud Data Teams (previously Periscope Data)"](https://www.sisense.com/product/data-teams/)
- if the references in [brackets] refer to 'materialized views' in Periscope, via --comment lines, 
- and if so, what [materialized views](https://dtdocs.sisense.com/article/materializing-views) are, 
- that the queries should work with Postgres, AWS Redshift (based on Postgres), etc and don't require using Periscope,

or, remove the brackets and use standard SQL.

**Pull request closed without merging**
