### PR TITLE
NGPVAN user guide v0

### PR DESCRIPTION
**Pull request by mayefsky**
This is a basic admin user guide for using @lperson's NGPVAN integration with Spoke.
One outstanding item: I do not know or know how to confidently get at all the specific keys one needs to flush from Redis when one adds or changes their VAN API key. If one of you knows what they are, that would be helpful to add.

# Checklist:

(This change is just documentation)

### CODE REVIEW

**Comment by maxkc** [comment]
@bobbyoderek let me know if we can be helpful at all in building out this documentation more!

**Comment by schuyler1d** [comment]
@lperson @Frydafly 
Could one of you take a look at this PR?

**Comment by Frydafly** [comment]
Cool! Something that might make this documentation even more useful is if we could include the json variables needed in order to integrate with MyCampaign in VAN, which is different from MyVoters but still used by some organizations. The below goes within the {} brackets in the "features" column for the corresponding organization in the database.

"NGP_VAN_DATABASE_MODE":1,"MESSAGE_HANDLERS":"ngpvan"

Also, some organizations run into the issue of having too many survey questions in VAN, and then Spoke fails to pull them up in the action handler section. The way we have resolved this is by adding this to features: 

"NGP_VAN_ELECTION_CYCLE_FILTER":"2021"

Filtering to the current year limits the options and fixes this issue.

**Review by Frydafly — APPROVED** [review]
This looks great!

**Comment by Frydafly** [comment]
@schuyler1d what do you think about merging this documentation! I think it'll be really helpful. 

(cc: @lperson & @maxkc ?)

**Pull request merged**
